export const icons = [
  {
    name: "HTML",
    pathIcon: "html5.svg",
    color: "orange",
    category: "frontend",
  },
  { name: "CSS", pathIcon: "Css.svg", color: "blue", category: "frontend" },
  {
    name: "TailwindCSS",
    pathIcon: "tailwindcss.svg",
    color: "tailwind",
    category: "frameworks",
  },
  {
    name: "JavaScript",
    pathIcon: "javascript.svg",
    color: "yellow",
    category: "frontend",
  },
  {
    name: "TypeScript",
    pathIcon: "typescript.svg",
    color: "typescript",
    category: "frontend",
  },
  {
    name: "React / React Native",
    pathIcon: "React_dark.svg",
    color: "blue",
    category: "frameworks",
  },
  { name: "Vite", pathIcon: "vitejs.svg", color: "vite", category: "frontend" },
  {
    name: "Next.js",
    pathIcon: "nextjs_icon_dark.svg",
    color: "default",
    category: "frameworks",
  },
  {
    name: "Express",
    pathIcon: "Express.js_light.svg",
    color: "default",
    category: "backend",
  },
  {
    name: "SqlServer",
    pathIcon: "sql-server.svg",
    color: "SQLServer",
    category: "backend",
  },
  { name: "Jira", pathIcon: "jira.svg", color: "jira", category: "tools" },
  { name: "Git", pathIcon: "git.svg", color: "git", category: "tools" },
  {
    name: "Postman",
    pathIcon: "postman.svg",
    color: "postman",
    category: "tools",
  },
];
